[workspace]
resolver = "2"
members = [
    "crates/netpng-core",
    "crates/pngcrop",
    "crates/pngcat",
    "crates/pngtrim",
    "crates/pngcompose",
    "crates/pnginfo",
    "crates/pnginvert",
    "crates/pngflip",
    "crates/pngrotate",
    "crates/pngscale",
    "crates/pngnorm",
    "crates/pngdist",
    "crates/pngreduce",
    "crates/pngchroma",
    "crates/pngblur",
    "crates/pngview",
    "crates/pngdecontaminate",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
